version: '3.8'

services:
  sql-mcp:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=${DB_HOST:-localhost}
      - DB_PORT=${DB_PORT:-5432}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env
    restart: unless-stopped
